import Navbar from '@/components/Navbar'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-gray-100 flex flex-col items-center'>
        <main className=' w-full font-nuni min-h-screen max-w-4xl'>
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  )
}
